/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibSgxJava_SgxFunction */

#ifndef _Included_LibSgxJava_SgxFunction
#define _Included_LibSgxJava_SgxFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibSgxJava_SgxFunction
 * Method:    jni_initialize_enclave
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LibSgxJava_SgxFunction_jni_1initialize_1enclave
  (JNIEnv *, jobject);

/*
 * Class:     LibSgxJava_SgxFunction
 * Method:    jni_ecall_sgx_read_rand
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_LibSgxJava_SgxFunction_jni_1ecall_1sgx_1read_1rand
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     LibSgxJava_SgxFunction
 * Method:    jni_sgx_destroy_enclave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LibSgxJava_SgxFunction_jni_1sgx_1destroy_1enclave
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
